FROM ubuntu

MAINTAINER shendric

RUN apt-get update && apt-get install -y emacs

CMD ["/usr/bin/emacs", "-f", "5x5"]

#5x5
#blackbox
#solitaire
#adventure
#gomoku
#life
#snake
#tetris

# docker build -t games .

# docker run --rm -ti games
